# GENERAL
general {
    disable_loading_bar = false
    hide_cursor = true
}
# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/assets/device-is-encrypted.png
    color = rgb(0, 0, 0)
    brightness = 0
}

# INPUT FIELD
input-field {
    monitor =
    size = 1000, 50
    outline_thickness = 2
    dots_size = 2
    dots_spacing = -0.1
    dots_center = false
    outer_color = rgba(0,0,0,0)
    inner_color = rgba(0,0,0,0)
    font_color = rgb(0,0,0)
    dots_text_format = █
    dots_rounding = 0
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    check_color = rgba(0,0,0,0)
    fail_color = rgba(0,0,0,0)
    fail_text = <b>Access denied. <i>($ATTEMPTS)</i></b>
    position = 0, 0
    halign = left
    valign = bottom
}
