# stop the teardrop noise
enable_audio_bell no
# for nnn preview
#   see https://old.reddit.com/r/KittyTerminal/comments/l2je2r
allow_remote_control yes
listen_on unix:/tmp/kitty
# NOTE: /tmp/kitty-<PID> is referenced in hyprkittycwd in my hyprland config.

# NOTE: i also use kitty patches, see https://funroll.swomf.com/conf/terminal

# // LINK OPENING STUFF
open_url_with default
mouse_map alt+left release grabbed,ungrabbed mouse_click_url

# // FIREFOX-ESQUE CONTROLS

# touchpad scroll
touch_scroll_multiplier 3.0


# // FOOT-ESQUE CONTROLS

# disable confirmation dialog
confirm_os_window_close 0

# numpad page scroll
map KP_Prior scroll_page_up
map KP_Next scroll_page_down
map ctrl+shift+KP_Home scroll_home
map ctrl+shift+KP_End scroll_end

# box highlight
mouse_map ctrl+left press ungrabbed mouse_selection rectangle

# zoom without the default Shift modifier for kitty single instance
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

# search scrollback, like foot's ctrl+shift+r
map ctrl+shift+r show_scrollback
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER +'/'

# font
font_family SauceCodePro Nerd Font

# foot's solid, non-blinking block cursor
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

# disable automatic config reload; saves 12 MB
# (reload is CTRL+SHIFT+F5)
auto_reload_config -1

# selection coloring, make it not an ugly beige
selection_foreground none
selection_background none
background #000000

# zoom w/o shift modifier, for single-instance kitty
map ctrl+equal       change_font_size current +2.0
map ctrl+plus        change_font_size current +2.0
map ctrl+kp_add      change_font_size current +2.0
map ctrl+minus       change_font_size current -2.0
map ctrl+kp_subtract change_font_size current -2.0
map ctrl+backspace   change_font_size current 0

# normal/regular colors (based on EndeavourOS colors)
color0  #000000
color1  #ff7f7f
color2  #7f3fbf
color3  #cc3980
color4  #7fbaff
color5  #7f3fbf
color6  #7f7fff
color7  #cdcccb

# bright colors
color8  #99c9c9
color9  #ff7f7f
color10 #7fbaff
color11 #ff7f7f
color12 #7f7fff
color13 #7f3fbf
color14 #7f7fff
color15 #e3e3ea
