#!/bin/bash

main_monitor="LVDS-1"

rotation_selection=$1

# Take arguments
if [ -n "$1" ]; then
  wlr-randr --output ${main_monitor} --transform ${1}
  exit 0
fi

# Spin counterclockwise
case $(wlr-randr | awk '/Transform/ {print $2}') in
  normal)
    wlr-randr --output ${main_monitor} --transform 90
    ;;
  90)
    wlr-randr --output ${main_monitor} --transform 180
    ;;
  180)
    wlr-randr --output ${main_monitor} --transform 270
    ;;
  270)
    wlr-randr --output ${main_monitor} --transform normal
    ;;
  *)
    ;;
esac
