#!/usr/bin/env sh

class=
app=
bring_to_workspace=

usage() {
  cat <<EOF
  $0 usage:
  -a   specify app, as seen in PATH
  (e.g. easyeffects)
  -c   specify class iff different from app,
  as seen in hyprctl clients
  (e.g. com.github.wwmm.easyeffects)
  -b   brings focused app to workspace also
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
  -a | --app)
    app="$2"
    shift
    ;;
  -c | --class)
    class="$2"
    shift
    ;;
  -b | --bring_to_workspace) bring_to_workspace="yes" ;;
  --)
    shift
    break
    ;;
  *)
    echo "$0: unrecognized option $1" 1>&2
    usage
    exit 1
    ;;
  esac
  shift
done
if [ -z "$class" ] && [ -z "$app" ] && [ -z "$bring_to_workspace" ]; then
  usage
  exit 1
fi

if [ -z "$class" ]; then
  class="$app"
fi

workspace="$(hyprctl clients -j | jq '.[] | select(.class == "'"$class"'") | .workspace.id')"

if [ -n "$workspace" ]; then
  if [ -z "$bring_to_workspace" ]; then
    hyprctl --batch "
    dispatch workspace $workspace;
    dispatch focuswindow class:$app
    "
  else
    hyprctl --batch "
    dispatch movetoworkspace $workspace;
    dispatch focuswindow class:$app
    "
  fi
elif [ -n "$app" ]; then
  exec "$app"
fi
