#!/usr/bin/env sh

class=
app=
send_to_workspace=

usage() {
  cat <<EOF
  $0 usage:
  -a, --app     specify app, as seen in PATH
                (e.g. easyeffects)
  -c, --class   specify class iff different from app,
                as seen in hyprctl clients
                (e.g. com.github.wwmm.easyeffects)
  -s, --send-to-workspace
                sends focused app to workspace instead
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
  -a | --app)
    app="$2"
    shift
    ;;
  -c | --class)
    class="$2"
    shift
    ;;
  -s | --send-to-workspace) send_to_workspace="yes" ;;
  --)
    shift
    break
    ;;
  *)
    echo "$0: unrecognized option $1" 1>&2
    usage
    exit 1
    ;;
  esac
  shift
done
if [ -z "$class" ] && [ -z "$app" ] && [ -z "$send_to_workspace" ]; then
  usage
  exit 1
fi

if [ -z "$class" ]; then
  class="$app"
fi

workspace="$(hyprctl clients -j | jq '.[] | select(.class == "'"$class"'") | .workspace.id')"

if [ -n "$workspace" ]; then
  if [ -z "$send_to_workspace" ]; then
    hyprctl --batch "
    dispatch workspace $workspace;
    dispatch focuswindow class:$app
    "
  else
    hyprctl --batch "
    dispatch movetoworkspacesilent $workspace;
    "
  fi
elif [ -n "$app" ]; then
  exec "$app"
fi
