#!/usr/bin/env sh

app="$1"
workspace="$(hyprctl clients -j | jq '.[] | select(.class == "'"$app"'") | .workspace.id')"

if [ -n "$workspace" ]; then
  hyprctl --batch "
    dispatch workspace $workspace;
    dispatch focuswindow class:$app
  "
elif [ -n "$2" ]; then
  exec "$2"
elif [ -n "$app" ]; then
  exec "$app"
else
  printf "No app provided.\n" >&2
fi
