#!/usr/bin/env sh

transform="$(
  hyprctl monitors | awk '/eDP-1/ {
    while (getline > 0 && !/transform/) {}
    print $2
  }'
)"

if [ "$transform" = "0" ] || [ "$transform" = "2" ]; then
  # Horizontally-long screen
  hyprlock
else
  # Vertically-oriented screen
  hyprlock -c ~/.config/hypr/hyprlock-vertical.conf
fi
