#!/usr/bin/env sh

# FIXME: with multiple monitors, spinning arbitrarily will cause
#        collision i.e. cursor shows up on both monitors

monitor="$(hyprctl activeworkspace -j | jq '.monitor' -r)"
monitor_json="$(hyprctl monitors -j | jq '.[] | select(.name == "'"${monitor}"'")')"

scale="$(echo "${monitor_json}" | jq '.scale')"
width="$(echo "${monitor_json}" | jq '.width')"
height="$(echo "${monitor_json}" | jq '.height')"
refresh_rate="$(echo "${monitor_json}" | jq '.refreshRate')"

# spin screen and touchscreen via hyprctl batch
# https://wiki.hyprland.org/Configuring/Variables/#touchdevice

rot() {
  direction=
  wallpaper=
  # e.g. rot up
  case $1 in
  down)
    direction=0
    wallpaper="$HOME/.config/hypr/assets/lagtrain.png"
    ;;
  right)
    direction=1
    wallpaper="$HOME/.config/hypr/assets/rainyboots.png"
    ;;
  up)
    direction=2
    wallpaper="$HOME/.config/hypr/assets/lagtrain.png"
    ;;
  left)
    direction=3
    wallpaper="$HOME/.config/hypr/assets/rainyboots.png"
    ;;
  esac

  hyprctl keyword monitor "${monitor}","${width}"x"${height}"@"${refresh_rate}",0x0,"${scale}",transform,"${direction}"
  # touch device rotation doesn't appear reliable
  #keyword input:touchdevice:transform ${direction};"
  # hyprctl doesnt work with batch and crashes if immediately
  # after a rotation (comment: is this still true?)
  current_wallpaper="$(hyprctl hyprpaper listactive | awk "/${monitor}/ {print \$3}")"
  if [ ! "$current_wallpaper" = "$(realpath "${wallpaper}")" ]; then
    sleep .15 && hyprctl hyprpaper wallpaper "${monitor}","${wallpaper}"
  fi

}

# Take arguments
if [ -n "$1" ]; then
  rot "$1"
  exit 0
fi

# Spin counterclockwise
case $(wlr-randr | awk '/Transform/ {print $2}') in
normal)
  rot left
  ;;
270)
  rot up
  ;;
180)
  rot right
  ;;
90)
  rot down
  ;;
*) ;;
esac
