# oh my zsh ################################################################### oh my zsh
export ZSH="/usr/share/zsh/site-contrib/oh-my-zsh"
ZSH_THEME="netmask"
plugins=(git)
EDITOR=nvim
source $ZSH/oh-my-zsh.sh

# paths ####################################################################### paths
# cargo
export PATH="$PATH:$HOME/.cargo/bin"
# flutter
export PATH="$PATH:$HOME/flutter/flutter/bin"
# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
# local/bin
export PATH="${PATH}:${HOME}/.local/bin"
# nvidia cuda toolkit
export PATH="${PATH}:/opt/cuda/bin"

# completions ################################################################# completions
eval "$(zoxide init zsh)"
source /usr/share/zsh/site-functions/zsh-autosuggestions.zsh
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# fixes ####################################################################### fixes
# GPG_TTY: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=doc/gpg-agent.texi;h=42ac84019e79e9e7845a673af5e5a3e154c5ba36;hb=HEAD#l96
#          fixes invalid ioctl error during gpg-based git sign
export GPG_TTY=$(tty)
# Wayland hint: https://github.com/flathub/org.signal.Signal/commit/11cc6bbe9581a8ec9ba21b96d7582ed024db7570
#               fixes wayland-compatible electron apps from erroneously using x11
#               NOTE: some electron apps may need --enable-gpu or --disable-gpu
export ELECTRON_OZONE_PLATFORM_HINT=auto
# webkit: nvidia sometimes makes things straight up invisible
# https://askubuntu.com/a/1493214
alias foliate='env GTK_THEME=Blackbriar-Dark-compact:dark foliate'

# env vars for Gentoo:app-emulation/wine-proton
#   See /var/db/repos/gentoo/app-emulation/wine-proton/files/README.gentoo
export WINEFSYNC=1                # requires linux kernel >=5.16
export WINE_LARGE_ADDRESS_AWARE=1 # helps w/ 32bit memory
# WINEPREFIX=/path/to setup_dxvk.sh install --symlink # requires app-emulation/dxvk
# WINEPREFIX=/path/to setup_vkd3d_proton.sh install --symlink # requires app-emulation/vkd3d-proton

# funcs ####################################################################### funcs

alias musescore=~/files/app/musescore/squashfs-root/AppRun # musescore squashfs
alias py=python3                 # match win10 python
alias R='R --no-save'            # disable "save workspace image?" prompt
alias rcs='sudo rc-service'
alias rcu='sudo rc-update'
alias lynx='lynx -vikeys'
alias t=tree
alias j=just
alias bctl=bluetoothctl

lofigirl() {mpv "https://youtube.com/watch?v=jfKfPfyJRdk"} # hiphop radio
tldr() {curl cht.sh/"$1"} # silly manpage skip
ytw() {yt-dlp "$1" -o - | mpv -}
condify () {source ~/miniconda3/etc/profile.d/conda.sh}

# run a command and silently detach e.g. stfu chromium
#stfu() {
#  if [ -z "$1" ]; then
#    echo "Usage: stfu <program or alias> [arguments...]"
#    return 1
#  fi
#
#  if [[ "$(type "$1" | cut -d' ' -f2-5)" == "is a shell function" ]]; then
#    # eval can be buggy with quotes; this is a backup
#    # in case we're running something like `stfu stfu ls`
#    eval "$@" &>/dev/null &
#  else
#    # alias expansion support instead of raw nohup
#    # do not add quotations on left; keep command distinct
#    #   e.g. nohup "env a=b" "ls" will fail
#    nohup $(whence $1) "${@:2}" &>/dev/null &
#  fi
#
#  disown
#}
#_stfu() {
#  # Since we take a command as an argument, we need to
#  # shift the _normal completion function to the next word.
#  shift words
#  (( CURRENT-=1 ))
#  _normal
#}
#compdef _stfu stfu

# read battery and date. poor man's taskbar
ck() {
  tput civis
  trap 'tput cnorm; return 1' INT TERM
  while true; do
    printf "%s%% | %s" "$(cat /sys/class/power_supply/BAT0/capacity)" "$(date +"%Y-%m-%d %T %a")"
    sleep 1;
    printf "\r"
  done
}

# shows a rgb value in terminal
hexshow() {
  is8bit() { # inputs: any. outputs: is number in [0,255]
    [[ "$1" =~ ^[0-9]{1,3}$ ]] && (( $1 >= 0 && $1 <= 255 ))
  }
  cprint() { # inputs: r g b
    printf "\e[48;2;${1};${2};${3}m    \e[0m\n"
    printf "\e[48;2;${1};${2};${3}m    \e[0m\n"
  }
  if [[ "$1" =~ ^[0-9A-Fa-f]{6}$ ]]; then
    local color="#$1"
    local r=$(( 16#${color:1:2} ))
    local g=$(( 16#${color:3:2} ))
    local b=$(( 16#${color:5:2} ))
    cprint "$r" "$g" "$b"
  elif is8bit "$1" && is8bit "$2" && is8bit "$3"; then
    cprint "$1" "$2" "$3"
  else
    echo "Usage: hexshow RRGGBB or hexshow R G B"
  fi
}

mkgplv3() {
  set -x
  trap 'set +x; return 1' INT TERM
  git init
  curl https://www.gnu.org/licenses/gpl-3.0.txt > LICENSE
  git add LICENSE
  git commit -m "license: add gplv3"
  set +x
}


# nnn config ################################################################## nnn

f () {
  export NNN_FIFO="/tmp/nnn.fifo"   # buffer for previews
  if kitten icat --detect-support &>/dev/null; then
    export NNN_PLUG="p:preview-tui" # install -D {/usr/share,~/.config}/nnn/plugins/preview-tui
  fi                                  # type `;p` in kitty for preview.
  export SPLIT='v'                  # split kitty vertically


  if [ ! "${NNNLVL:-0}" -eq 0 ]; then
    echo "nnn is already running"
    return
  fi

  # from https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash_sh_zsh
  # The behaviour is set to cd on quit (nnn checks if NNN_TMPFILE is set)
  # If NNN_TMPFILE is set to a custom path, it must be exported for nnn to
  # see. To cd on quit only on ^G, remove the "export" and make sure not to
  # use a custom path, i.e. set NNN_TMPFILE *exactly* as follows:
  #      NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
  export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

  # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
  # stty start undef
  # stty stop undef
  # stty lwrap undef
  # stty lnext undef

  # The command builtin allows one to alias nnn to n, if desired, without
  # making an infinitely recursive alias
  command nnn "$@"

  if [ -f "$NNN_TMPFILE" ]; then
    . "$NNN_TMPFILE"
    rm -f -- "$NNN_TMPFILE" > /dev/null
  fi
}

# random color vars :3 ######################################################## colors

CDEF="\033[0m"                                     # default color
CCIN="\033[0;36m"                                  # info color
CGSC="\033[0;32m"                                  # success color
CRER="\033[0;31m"                                  # error color
CWAR="\033[0;33m"                                  # warning color
b_CDEF="\033[1;37m"                                # bold default color
b_CCIN="\033[1;36m"                                # bold info color
b_CGSC="\033[1;32m"                                # bold success color
b_CRER="\033[1;31m"                                # bold error color
b_CWAR="\033[1;33m"                                # bold warning color
