# oh my zsh ###################################################################
export ZSH="/usr/share/zsh/site-contrib/oh-my-zsh"
ZSH_THEME="netmask"
plugins=(git)
EDITOR=nvim
source $ZSH/oh-my-zsh.sh

# paths #######################################################################
# cargo
export PATH="$PATH:$HOME/.cargo/bin"
# flutter
export PATH="$PATH:$HOME/flutter/flutter/bin"
# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
# local/bin
export PATH="${PATH}:${HOME}/.local/bin"

# completions #################################################################
eval "$(zoxide init zsh)"
source /usr/share/zsh/site-functions/zsh-autosuggestions.zsh
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# fixes #######################################################################
# GPG_TTY: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=doc/gpg-agent.texi;h=42ac84019e79e9e7845a673af5e5a3e154c5ba36;hb=HEAD#l96
#          fixes invalid ioctl error during gpg-based git sign
export GPG_TTY=$(tty)
# Wayland hint: https://github.com/flathub/org.signal.Signal/commit/11cc6bbe9581a8ec9ba21b96d7582ed024db7570
#               fixes wayland-compatible electron apps from erroneously using x11
#               NOTE: some electron apps may need --enable-gpu or --disable-gpu
export ELECTRON_OZONE_PLATFORM_HINT=auto

# funcs #######################################################################
alias py=python3

# silly man page skip
export tldr() {curl cht.sh/$1}

# run a command and silently detach e.g. stfu chromium
stfu() {
  if [ -z "$1" ]; then
    echo "Usage: stfu <program or alias> [arguments...]"
    return 1
  fi

  if [[ "$(type "$1" | cut -d' ' -f2-5)" == "is a shell function" ]]; then
    # eval can be buggy with quotes; this is a backup
    # in case we're running something like `stfu stfu ls`
    eval "$@" &>/dev/null &
  else
    # alias expansion support instead of raw nohup
    # do not add quotations on left; keep command distinct
    #   e.g. nohup "env a=b" "ls" will fail
    nohup $(whence $1) "${@:2}" &>/dev/null &
  fi

  disown
}
_stfu() {
  # Since we take a command as an argument, we need to
  # shift the _normal completion function to the next word.
  shift words
  (( CURRENT-=1 ))
  _normal
}
compdef _stfu stfu

# read battery and date. poor man's taskbar
ck() {
  tput civis
  trap 'tput cnorm; return 1' INT TERM
  while true; do
    printf "%s%% | %s" "$(cat /sys/class/power_supply/BAT0/capacity)" "$(date +"%Y-%m-%d %T %a")"
    sleep 1;
    printf "\r"
  done
}

# shows a rgb value in terminal
hexshow() {
  is8bit() { # inputs: any. outputs: is number in [0,255]
    [[ "$1" =~ ^[0-9]{1,3}$ ]] && (( $1 >= 0 && $1 <= 255 ))
  }
  cprint() { # inputs: r g b
    printf "\e[48;2;${1};${2};${3}m    \e[0m\n"
    printf "\e[48;2;${1};${2};${3}m    \e[0m\n"
  }
  if [[ "$1" =~ ^[0-9A-Fa-f]{6}$ ]]; then
    local color="#$1"
    local r=$(( 16#${color:1:2} ))
    local g=$(( 16#${color:3:2} ))
    local b=$(( 16#${color:5:2} ))
    cprint "$r" "$g" "$b"
  elif is8bit "$1" && is8bit "$2" && is8bit "$3"; then
    cprint "$1" "$2" "$3"
  else
    echo "Usage: hexshow RRGGBB or hexshow R G B"
  fi
}

mkgplv3() {
  set -x
  trap 'set +x; return 1' INT TERM
  git init
  curl https://www.gnu.org/licenses/gpl-3.0.txt > LICENSE
  git add LICENSE
  git commit -m "license: add gplv3"
  set +x
}
