#!/usr/bin/env bash

set -euo pipefail

# cool ass trick https://tldp.org/LDP/abs/html/parameter-substitution.html
INPUT="${1:?Usage: $0 <input img> [output.gif]}"
OUTPUT="${2:-${INPUT%.*}.gif}"
PALETTE="$(mktemp /tmp/palette_XXXXXX.png)" # ffmpeg palette guesswork for fidelity
trap 'rm "$PALETTE"' EXIT
# https://ffmpeg.org/ffmpeg-filters.html
ffmpeg -loglevel warning -i "$INPUT" -vf palettegen -y "$PALETTE"
ffmpeg -loglevel warning -i "$INPUT" -i "$PALETTE" -filter_complex paletteuse \
  -frames:v 1 -loop 0 -y "$OUTPUT"
echo "Done: $OUTPUT"
