# stop the teardrop noise
enable_audio_bell no
# for nnn preview
#   see https://old.reddit.com/r/KittyTerminal/comments/l2je2r
allow_remote_control yes
listen_on unix:/tmp/kitty

# numpad page scroll
map KP_Prior scroll_page_up
map KP_Next scroll_page_down
map ctrl+shift+KP_Home scroll_home
map ctrl+shift+KP_End scroll_end
