#!/bin/bash

main_monitor="eDP-1"

# spin screen and touchscreen via hyprctl batch
# https://wiki.hyprland.org/Configuring/Variables/#touchdevice
#
# bug: on fractional display hyprpaper may be incorrectly sized after
#      a spin. in that case, just repeat whatever orientation you're on
#      e.g. right side up and hyprpaer is wrong? go right side up again
declare -A rotArray
rotArray[down]="0"
rotArray[right]="1"
rotArray[up]="2"
rotArray[left]="3"

rot() {
  # e.g. rot up
  arg="${rotArray[$1]}"
  hyprctl --batch \
    "keyword monitor eDP-1,1920x1080@60,0x0,1.2,transform,${arg};\
    keyword input:touchdevice:transform ${arg};"
}

# Take arguments
if [ -n "$1" ]; then
  rot "$1"
  exit 0
fi

# Spin counterclockwise
case $(wlr-randr | awk '/Transform/ {print $2}') in
normal)
  rot left
  ;;
270)
  rot up
  ;;
180)
  rot right
  ;;
90)
  rot down
  ;;
*) ;;
esac
