#!/usr/bin/env bash

main_monitor="eDP-1"

# spin screen and touchscreen via hyprctl batch
# https://wiki.hyprland.org/Configuring/Variables/#touchdevice

declare -A rotArray
rotArray[down]="0 $HOME/.config/hypr/assets/lagtrain.png"
rotArray[right]="1 $HOME/.config/hypr/assets/rainyboots.png"
rotArray[up]="2 $HOME/.config/hypr/assets/lagtrain.png"
rotArray[left]="3 $HOME/.config/hypr/assets/rainyboots.png"

rot() {
  # e.g. rot up
  IFS=' ' read -r -a args <<<"${rotArray[$1]}"
  direction="${args[0]}"
  wallpaper="${args[1]}"
  hyprctl --batch \
    "keyword monitor ${main_monitor},1920x1080@60,0x0,1,transform,${direction};\
    keyword input:touchdevice:transform ${direction};"
  # hyprctl doesnt work with batch and crashes if immediately
  # after a rotation
  current_wallpaper="$(hyprctl hyprpaper listactive | awk "/${main_monitor}/ {print \$3}")"
  if [[ ! "$current_wallpaper" == "$(realpath "${wallpaper}")" ]]; then
    sleep .15 && hyprctl hyprpaper wallpaper eDP-1,"${wallpaper}"
  fi

}

# Take arguments
if [ -n "$1" ]; then
  rot "$1"
  exit 0
fi

# Spin counterclockwise
case $(wlr-randr | awk '/Transform/ {print $2}') in
normal)
  rot left
  ;;
270)
  rot up
  ;;
180)
  rot right
  ;;
90)
  rot down
  ;;
*) ;;
esac
