# ######## Window rules ########
# windowrule = noblur,.*
windowrule = noblur, class:^(org.musescore.*)$     # music transcription
windowrule = noblur, class:^(swappy)$              # pic
windowrule = noblur, class:^(Nsxiv)$               # pic
windowrule = noblur, class:^(krita)$               # practice drawing
windowrule = noblur, class:^(org.vinegarhq.Sober)$ # practice drawing
windowrule = noblur, class:^(firefox.*)$           # overlay videos
windowrule = noblur, class:^(Mullvad Browser)$     # overlay videos
# windowrule = opacity 0.89 override 0.89 override, .* # Applies transparency to EVERY WINDOW
windowrule = float, class:^(blueberry.py)$
windowrule = float, class:^(steam)$
windowrule = float, class:^(guifetch)$ # FlafyDev/guifetch
windowrule = noblur, class:^(gimp.*)$
windowrule = tile,class:(dev.warp.Warp)
# windowrulev2 = opacity 0.9 0.6,class:^(foot)$
windowrule = opacity 0.6 override, tag:blurry

windowrule = noblur, title:piece-of-glass
windowrule = bordercolor rgb(000000), title:piece-of-glass
windowrule = bordersize 1, title:piece-of-glass
windowrule = decorate, title:piece-of-glass

# Dialogs
windowrule = float,title:^(Open File)(.*)$
windowrule = float,title:^(Select a File)(.*)$
windowrule = float,title:^(Choose wallpaper)(.*)$
windowrule = float,title:^(Open Folder)(.*)$
windowrule = float,title:^(Save As)(.*)$
windowrule = float,title:^(Library)(.*)$

# Tearing
windowrule=immediate,class:^(.*\.exe)
windowrule=immediate,class:(steam_app)

# No shadow for tiled windows
windowrule = noshadow,floating:0

# Fix for Gimp (a bug causes cursor
# to lock at center of window when
# changing brush color)
windowrule = suppressevent activatefocus activate, class:^(gimp.*)$

# ######## Layer rules ########
layerrule = xray 1, .*
# layerrule = noanim, .*
layerrule = noanim, walker
layerrule = noanim, selection # e.g. slurp
layerrule = noanim, anyrun
layerrule = noanim, launcher # fuzzel
layerrule = noanim, indicator.*
layerrule = noanim, hyprpicker
#layerrule = blur, shell:*
layerrule = ignorealpha 0.6, shell:*

layerrule = noanim, noanim
#layerrule = blur, gtk-layer-shell
layerrule = ignorezero, gtk-layer-shell
#layerrule = blur, launcher
layerrule = ignorealpha 0.5, launcher
#layerrule = blur, notifications
layerrule = ignorealpha 0.69, notifications
